---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: api-gateway
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: api-gateway
  rollback:
    enable: true
  chart:
    repository: https://payticon-charts.devticon.com
    name: api-gateway
    version: v1.0.11
  values:
    gql:
      playground: true
    image:
      repository: eu.gcr.io/payticon-261013/payticon-api-gateway
      tag: v1.0.11
    ingress:
      enabled: true
      hosts:
      - host: api.staging.payticon.com
        paths:
        - ""
      annotations:
        kubernetes.io/ingress.class: traefik
        ingress.kubernetes.io/whitelist-source-range: 18.197.220.18/32
    resources:
      requests:
        cpu: "5m"