---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: api-gateway
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: api-gateway
  chart:
    repository: https://payticon-charts.devticon.com
    name: api-gateway
    version: v1.0.7
  values:
    image:
      repository: eu.gcr.io/payticon-261013/payticon-api-gateway
      tag: v1.0.9

