---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: import
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: import
  chart:
    repository: https://payticon-charts.devticon.com
    name: import
    version: v1.0.3
  values:
    image:
      repository: eu.gcr.io/payticon-261013/payticon-import
      tag: v1.0.3
    resources:
      requests:
        cpu: "0.5"