---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: import
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: import
  chart:
    repository: https://payticon-charts.devticon.com
    name: import
    version: 1.0.2
  values:
    image:
      repository: eu.gcr.io/payticon-261013/payticon-import
      tag: 1.0.2
