---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mock-supplier
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: mock-supplier
  chart:
    repository: https://payticon-charts.devticon.com
    name: mock-supplier
    version: v1.0.2
  values:
    image:
      repository: eu.gcr.io/payticon-261013/payticon-mock-supplier
      tag: v1.0.2

