---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: user
#  namespace: app
  annotations:
    fluxcd.io/automated: "true"
#    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: user
  chart:
    repository: https://payticon-charts.devticon.com
    name: user
    version: 1.0.7
  values:
    adminPassword: "Test1234"
