---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: order
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicaCount: 4
  releaseName: order
  chart:
    repository: https://payticon-charts.devticon.com
    name: order
    version: v1.2.14
  values:
    logLevel: debug
    image:
      repository: eu.gcr.io/payticon-261013/payticon-order
      tag: v1.2.14
    resources:
      requests:
        cpu: "30m"
        memory: "60M"
