---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: order-storage
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: order-storage
  chart:
    repository: https://payticon-charts.devticon.com
    name: order-storage
    version: v1.1.9
  values:
    postgresql:
      postgresPassword: Test1234
    image:
      repository: eu.gcr.io/payticon-261013/payticon-order-storage
      tag: v1.1.12
    resources:
      requests:
        cpu: "25m"
        memory: "80M"
