---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: partner
#  namespace: app
  annotations:
    fluxcd.io/automated: "true"
#    fluxcd.io/tag.chart-image: semver:~4.0
spec:
  releaseName: partner
  chart:
    repository: https://payticon-charts.devticon.com
    name: partner
    version: 1.2.6
  values:
    adminPassword: "Test1234"
