---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: partner
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: partner
  chart:
    repository: https://payticon-charts.devticon.com
    name: partner
    version: v1.0.2
  values:
    postgresql:
      postgresPassword: test1234
    image:
      repository: eu.gcr.io/payticon-261013/payticon-partner
      tag: v1.0.5
    resources:
      requests:
        cpu: "25m"
        memory: "80M"
