---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: partner
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: partner
  chart:
    repository: https://payticon-charts.devticon.com
    name: partner
    version: 1.0.2
  values:
    postgresql:
      postgresPassword: test1234
      persistence:
        enabled: false