---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: product
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: product
  chart:
    repository: https://payticon-charts.devticon.com
    name: product
    version: 1.2.7
  values:
    postgresql:
      postgresPassword: test1234
    image:
      repository: eu.gcr.io/payticon-261013/payticon-product
      tag: v1.2.12
    resources:
      requests:
        cpu: "25m"
        memory: "75M"
