---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: product
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: product
  chart:
    repository: https://payticon-charts.devticon.com
    name: product
    version: 1.2.6
  values:
    postgresql:
      postgresPassword: test1234
      persistence:
        enabled: false
