---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: rabbitmq
  rollback:
    enable: true
  chart:
    repository: https://payticon-charts.devticon.com
    name: rabbitmq
    version: 1.0.2
  values:
    image:
      repository: eu.gcr.io/payticon-261013/payticon-rabbitmq
      tag: 1.0.0
    resources:
      requests:
        cpu: "0.5"
      limits:
        memory: 512Mi
    service:
      port: 15672
    ingress:
      enabled: true
      hosts:
      - host: rabbitmq.staging.payticon.com
        paths:
        - ""
      annotations:
        kubernetes.io/ingress.class: traefik
        ingress.kubernetes.io/whitelist-source-range: 18.197.220.18/32
