---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: rabbitmq
  chart:
    repository: https://payticon-charts.devticon.com
    name: rabbitmq
    version: 1.0.0
  values:
    image:
      repository: eu.gcr.io/payticon-261013/payticon-rabbitmq
      tag: 1.0.0
