---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: soap-api
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: soap-api
  rollback:
    enable: true
    force: true
  chart:
    repository: https://payticon-charts.devticon.com
    name: soap-api
    version: v1.0.12
  values:
    endpoint: https://soap.staging.payticon.com
    apm:
      enabled: true
      serviceUrl: https://apm.devticon.com
      serviceName: payticon-soap-api
      env: payticon-staging
      captureBody: all
      errorOnAbortedRequests: true
      logUncaughtExceptions: true
    gql:
      playground: true
    image:
      repository: eu.gcr.io/payticon-261013/payticon-soap-api
      tag: v1.0.12
    ingress:
      enabled: true
      hosts:
      - host: soap.staging.payticon.com
        paths:
        - ""
      annotations:
        kubernetes.io/ingress.class: traefik
        ingress.kubernetes.io/whitelist-source-range: 18.197.220.18/32
      resources:
        requests:
          cpu: "150m"
          memory: "80M"