---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: soap-api
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: soap-api
  chart:
    repository: https://payticon-charts.devticon.com
    name: soap-api
    version: v1.0.10
  values:
    image:
      repository: eu.gcr.io/payticon-261013/payticon-soap-api
      tag: v1.0.10
