---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplier
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: supplier
  chart:
    repository: https://payticon-charts.devticon.com
    name: supplier
    version: v2.0.5
  values:
    logLevel: debug
    image:
      repository: eu.gcr.io/payticon-261013/payticon-supplier
      tag: v2.0.7
    values:
      postgresql:
        postgresPassword: test1234
    cipher:
      service: epay_code_cipher
      iv: 612D2DFF92F9854E
      key: 612D2DFF92F9854E
    resources:
      requests:
        cpu: "25m"
        memory: "80m"
