---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: user
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: user
  chart:
    repository: https://payticon-charts.devticon.com
    name: user
    version: v1.0.18
  values:
    adminPassword: "Test1234"
    image:
      repository: eu.gcr.io/payticon-261013/payticon-user
      tag: v1.0.18
    resources:
      requests:
        cpu: "10m"
        memory: "100M"